### ISSUE TITLE
Version. Flashing 

### ISSUE THREAD

**Issue by Person0z** [Magisk-Modules-Alt-Repo/oneplus-8series-9r-camera-unlocker#1]
I don't know what to put for the title, however I'm using Namless on A13. You can I use the android 12 version or will that cause me boot loop

**Comment by shadowstepxda** [comment]
@Person0z Not sure what you mean, but if you mean to ask whether Android 12 is supported, then yes, it is. Make sure you select the right firmware version that your custom ROM is using and you should be fine.
