### ISSUE TITLE
Extend support to OnePlus 9RT

### ISSUE THREAD

**Issue by DaniloJacques** [Magisk-Modules-Alt-Repo/oneplus-8series-9r-camera-unlocker#2]
OnePlus 9RT (Martini) has a good camera setup, bringing a IMX766 50MP main camera and a IMX481 16MP UW (nobody cares macro sensor).

With the ColorOS code merge to OOS, bugs appeared, performance dropped and some issues has occurred, so many users did rollback to OOS11. But there isn't a module to enable all 9RT cameras in GCam on OOS11.

Tried this module and the 9/9Pro one, and both gives FC when open any cameras (even the stock one). 

So, we, 9RT users, would love a module to make this work. I can give all files needed and test. Could it be possibile?

**Comment by shadowstepxda** [comment]
@DaniloJacques I have just packaged the modified libraries as a module; the actual modification of these libraries has not been done by me. Maybe the functionality can be ported over for OnePlus 9RT as well, but for that, you'll have to reach out to [Jeus Chrit](https://t.me/JeusChrit) on Telegram, who's the person to guide you.
