### ISSUE TITLE
OnePlus 7t Pro support?

### ISSUE THREAD

**Issue by Hellohi3654** [Magisk-Modules-Alt-Repo/oneplus-8series-9r-camera-unlocker#3]
Hi just wondering if you could add support for the OnePlus 7t pro 
I am happy to test
Or if you already know a way to get 48mp to work with gcam on the 7t pro
Thanks

**Comment by shadowstepxda** [comment]
Hi! Unfortunately I don't have the technical know-how to do that. Sorry!

**Comment by Hellohi3654** [comment]
> Hi! Unfortunately I don't have the technical know-how to do that. Sorry!

All good
I have moved back to OOS 11 now anyway
Can't stand all the bugs in OOS 12 and I use AC4 hardware decoding and 48mp photo mode so didn't like any AOSP ROMs
